PIOMASS year now 2022

diff --git a/UTIL/geo_sea_ice_volume/PIO/PIOMAS_fetch b/UTIL/geo_sea_ice_volume/PIO/PIOMAS_fetch
--- a/UTIL/geo_sea_ice_volume/PIO/PIOMAS_fetch
+++ b/UTIL/geo_sea_ice_volume/PIO/PIOMAS_fetch
@@ -17,6 +17,7 @@
 URL=http://psc.apl.uw.edu/wordpress/wp-content/uploads/schweiger/ice_volume/PIOMAS.vol.daily.1979.2019.Current.v2.1.dat.gz
 URL=http://psc.apl.uw.edu/wordpress/wp-content/uploads/schweiger/ice_volume/PIOMAS.vol.daily.1979.2020.Current.v2.1.dat.gz
 URL=http://psc.apl.uw.edu/wordpress/wp-content/uploads/schweiger/ice_volume/PIOMAS.vol.daily.1979.2021.Current.v2.1.dat.gz
+URL=http://psc.apl.uw.edu/wordpress/wp-content/uploads/schweiger/ice_volume/PIOMAS.vol.daily.1979.2022.Current.v2.1.dat.gz
 
 BASENAME=`basename $URL`
 
@@ -31,61 +32,104 @@ BASENAME=`basename $URL`
 # DATED_file_mtime=$BASENAME
 DATED_file_mtime=PIOMAS_dated
 
+# date_r $DATED_file_mtime
+ LOG=$0.log
+ # date | tee $LOG 
+ touch $LOG # wake up nfs disk
 
+
+# FUNC print dfate of file
 date_r()
 {
+	# this function does nothing, other than printing the date of the file
 	echo >&2 "# date -r $* # `date -r $@` " # mtime
 	# atime # unknown -flag || flag( "atimea, "{ ref_time = file.atime.get() }" 
 	# date -r "$@"
 }
 
 
-# date_r $DATED_file_mtime
- LOG=$0.log
- # date | tee $LOG 
- touch $LOG # wake up nfs disk
-
 # the exit code from curl is useless for Not Modified
 # both return OK 0
 # missing file does return non zero
 # so resort to grep
+# Feb got:
+# curl: (2) The requested URL returned error: 404 Not Found
+# other fails might be internet down, DNS fail, filename error, EINTR, ...
+
 #
 # nb every year the previous year remains un-modified
 # you would error after 5 weeks
 #
 # maybe libcurl or tcl-php-script node?
 
-if type curl
+if type curl > /dev/null 
 then
 	:
 else
+	# type curl # curl prints to stdout # errors to &2
+	echo >&2 "# FAIL # curl not found"
 	exit 1
 fi
 
-echo "# URL # $URL"
-date_r $DATED_file_mtime 
-echo
-if curl \
-	--remote-name \
-	--remote-time \
-	--time-cond $DATED_file_mtime \
-	-v \
-	--fail \
-	--fail-early \
-	"$URL" \
- 2>&1 | tee $LOG | grep Not.Modified
-then
-	:
-	date_r $DATED_file_mtime
-	exit 1
-else
+call_curl()
+{
+	echo "# URL # $URL"
+	date_r $DATED_file_mtime 
+	echo
+	curl \
+		--remote-name \
+		--remote-time \
+		--time-cond $DATED_file_mtime \
+		-v \
+		--fail \
+		--fail-early \
+		"$URL" \
+	 2>&1 | tee $LOG \
+	 > /dev/null
+	 # exit code not helpful
+}
+
+call_curl_and_check_log_text()
+{
+	if call_curl 
+	then
+		:
+	else
+		t=$?
+		return 1
+	fi
+	# 
+	# note that Not Modified is considered a FAIL
+	# you might want to PASS but FAIL # did work no new data file available
+	# 
+	LIST_FAILS="
+		Not.Modified
+		404.Not.Found
+		curl:.(.*)The.requested.URL.returned.error: 
+	"
+	for FAIL_MSG in $LIST_FAILS
+	do
+		echo >&2 "# checking for # '$FAIL_MSG'"
+		if grep "$FAIL_MSG" $LOG
+		then
+			echo >&2 "# FAIL # file not modifed since:"
+			date_r $DATED_file_mtime
+			return 1
+		fi
+	done
+
+	# curl sets the local file timestamp to the remote
 	touch -r $BASENAME $DATED_file_mtime
+	# tell user again for no good reason
 	ls -l $BASENAME $DATED_file_mtime
+	# show the logfile
 	cat $LOG
-	echo Maybe Downloaded
+	echo  Downloaded
 	date_r $DATED_file_mtime
 	exit 0
-fi
+}
+
+call_curl_and_check_log_text
 
 # unreached
 exit
