symc

diff --git a/libs_apps/MK_bin/fns_FAIL b/libs_apps/MK_bin/fns_FAIL
--- a/libs_apps/MK_bin/fns_FAIL
+++ b/libs_apps/MK_bin/fns_FAIL
@@ -76,8 +76,11 @@ fn_FAIL_TEXT() {
 fn_FAIL() {
 	fn_FAIL_TEXT "$@"
 	local errn="$?"
-	sleep 2
+
 	exit $errn
+	# $1 should be errno - or should errno be errno ?
+	echo >&2 "# FAIL # FAIL SHOULD HAVE EXITED "
+	sleep 2
 	return 1
 }
 
